export const storyExisting = [
  {
    "id_existing": 3,
    "title": "El Guardián de los Armarios Oscuros",
    "description": " En un pequeño pueblo rodeado de montañas, existía una leyenda sobre un ser terrorífico conocido como el Bogeyman. Se decía que este monstruo se escondía en los armarios oscuros de las casas, esperando a que los niños se durmieran para llevarlos consigo.\nLa historia comienza con una familia que se mudó a una casa antigua en el pueblo. El hijo menor, Timmy, comenzó a sentir una presencia extraña en su armario. Al principio, pensó que era solo su imaginación, pero pronto escuchó susurros y ruidos extraños provenientes del armario.\nUna noche, mientras su familia dormía, Timmy se levantó para investigar. Abrió la puerta del armario y encontró una figura sombría y deformada que lo miraba con ojos rojos brillantes. El Bogeyman.\nEl monstruo comenzó a hablar con una voz baja y rasposa, diciendo que había venido a llevarse a Timmy. El niño intentó huir, pero el Bogeyman lo atrapó y lo arrastró hacia el armario.\nAl día siguiente, la familia de Timmy lo buscó por toda la casa, pero no lo encontraron. La madre de Timmy recordó la leyenda del Bogeyman y supo que su hijo había sido llevado.\nLa familia intentó encontrar al Bogeyman, pero este se escondía en los armarios oscuros de las casas del pueblo, siempre fuera de alcance.\nAños después, los niños del pueblo seguían desapareciendo, y la leyenda del Bogeyman persistía. La gente decía que si escuchabas susurros en tu armario, el Bogeyman estaba cerca, esperando a que te durmieras.\nY si alguna vez escuchas tu nombre susurrado en la oscuridad, no respondas. El Bogeyman podría estar llamándote.",
    "imageUrl": "https://scontent.fzih1-1.fna.fbcdn.net/v/t39.30808-6/463794310_420101987861047_593098645405640609_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=e1afaa&_nc_ohc=w0DSdOxpxR8Q7kNvgHhbGkL&_nc_zt=23&_nc_ht=scontent.fzih1-1.fna&_nc_gid=ASb8mAic3zUZayL4-kkEAGc&oh=00_AYBNAiWD724D--HHreS-zGzYcAdQa4SmJcih65y--xmlsg&oe=67245EF9",
    "category": "Bogeyman",
  },
  {
    "id_existing": 5,
    "title": "La Noche de los Muertos",
    "description": "En una ciudad abandonada, un grupo de supervivientes se refugió en un edificio. De repente, un ruido ensordecedor llenó el aire. Los zombies habían encontrado su escondite. Mientras intentaban escapar, descubrieron que uno de ellos había sido mordido. La infección se propagó rápidamente. En medio del caos, una figura emergió de la oscuridad. Era el líder de los zombies, con ojos rojos brillantes. La noche se convirtió en un infierno.",
    "imageUrl": "https://scontent.fzih1-1.fna.fbcdn.net/v/t39.30808-6/463977813_420631681141411_6760054403746406694_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=e1afaa&_nc_ohc=iwAu1WCUzQkQ7kNvgHHGPuj&_nc_zt=23&_nc_ht=scontent.fzih1-1.fna&_nc_gid=AM1z54pV4hVc-jJ_WO3OMvQ&oh=00_AYCkGiUxJYjuEqggw5dODKABC2NFGK57bXI4JnpAGCOJvw&oe=67243CFE",
    "category": "Zombies",
  },
  {
    "id_existing": 6,
    "title": "La Noche de las Brujas",
    "description": "En un pueblo olvidado, tres amigas descubrieron un antiguo libro de hechizos en el bosque. Ansiosas por probar su poder, realizaron un ritual en la noche de luna llena. Pero pronto se dieron cuenta de que habían despertado a una fuerza maligna. Las sombras comenzaron a moverse y las voces susurrantes llenaron el aire. Las amigas se dieron cuenta de que habían sellado su propio destino. La noche se convirtió en un infierno y las brujas vinieron por ellas.",
    "imageUrl": "https://i.ibb.co/5KLZwpw/brujas.jpg",
    "category": "Brujas",
  },
  {
    "id_existing": 4,
    "title": "El Yōkai de la Niebla",
    "description": "En un pueblo rural japonés, una niebla espesa cubría la noche. Kenji, un joven curioso, se adentró en el bosque en busca de aventuras. De repente, una figura etérea emergió de la niebla. Era un Yōkai, un espíritu maligno con ojos rojos brillantes. Kenji intentó huir, pero el Yōkai lo envolvió en una niebla aún más densa. Cuando la niebla se disipó, Kenji había desaparecido. Al día siguiente, los aldeanos encontraron su cuerpo sin vida, con un mensaje grabado en la piel: \"El Yōkai me ha llevado.\"",
    "imageUrl": "https://i.ibb.co/tKZgmPN/genai-m4-ldc-lla-v3-upload-media-30637773-11-27-2024-20-55-07-415359-6621444927776445091.jpg",
    "category": "Yōkai",
  },
  {
    "id_existing": 1,
    "title": "La Noche Eterna de los Vampiros de Ravenwood",
    "description": "En el pueblo de Ravenwood, donde la niebla nunca se disipa, existía una leyenda sobre una familia de vampiros que habitaba en la mansión de los Ravenwood. La historia decía que si alguien se atrevía a entrar en la mansión después del anochecer, nunca saldría con vida. Emily, una joven periodista, decidió investigar la leyenda. Llegó a Ravenwood en una noche de luna llena y se dirigió hacia la mansión. Al acercarse, sintió una sensación de escalofrío que no podía explicar.\nAl entrar en la mansión, Emily encontró una habitación llena de retratos antiguos y una figura femenina sentada en un sofá, con ojos que parecían mirar directamente a su alma.\n\"Bienvenida, Emily\", dijo la mujer con una voz suave y helada. \"Me llamo Elizabeth Ravenwood. He estado esperándote.\"\nEmily se dio cuenta de que Elizabeth no era humana. Su piel era pálida, sus ojos brillaban en la oscuridad y sus dientes eran afilados.\n\"¿Qué quieres de mí?\", preguntó Emily. \"Quiero que te quedes conmigo\", respondió Elizabeth. \"Para siempre.\"\nEmily intentó huir, pero las puertas estaban bloqueadas. La mansión parecía tener vida propia y no la dejaría escapar. En ese momento, Emily supo que estaba condenada. La noche eterna de los vampiros de Ravenwood había comenzado. Y mientras Elizabeth se acercaba a ella, Emily sintió que su vida se esfumaba, consumida por la oscuridad eterna de los vampiros.\nFin.",
    "imageUrl": "https://i.ibb.co/wKF06Fr/freepik-candid-image-photography-natural-textures-highly-r-40879.jpg",
    "category": "Vampiros",
  },
  {
    "id_existing": 2,
    "title": "La Maldición del Hombre Lobo de Lunavilla",
    "description": "En el pueblo de Lunavilla, rodeado de bosques densos y niebla eterna, existía una leyenda sobre un hombre lobo que azotaba la región. La gente decía que durante las noches de luna llena, un hombre llamado Leonardo se transformaba en una bestia feroz que atacaba a cualquier ser vivo que se cruzara en su camino.\n\nLa historia comenzó cuando Leonardo, un joven solitario y melancólico, se mudó a Lunavilla en busca de paz. Sin embargo, pronto descubrió que algo oscuro y primitivo se escondía dentro de él, algo que solo emergía bajo la luz de la luna llena.\n\nUna noche, mientras caminaba por el bosque, Leonardo sintió el cambio. Su cuerpo comenzó a doler, sus sentidos se agudizaron y su mente se llenó de una sed de sangre insaciable. Se transformó en un lobo gigantesco, con ojos rojos brillantes y una fuerza sobrenatural.\n\nA partir de ese momento, Leonardo se convirtió en una bestia que aterrorizó a Lunavilla. La gente se escondía en sus casas durante las noches de luna llena, mientras el hombre lobo merodeaba por las calles, buscando su próxima víctima.\n\nUn grupo de valientes decidieron enfrentar al monstruo, pero pronto descubrieron que la bestia era invencible. Solo uno de ellos, una joven llamada Sofía, logró escapar con vida.\n\nSofía descubrió que la única forma de detener al hombre lobo era encontrar el origen de la maldición. Después de investigar, descubrió que la culpa era de un antiguo hechicero que había maldecido a la familia de Leonardo.\n\nCon la ayuda de un anciano sabio, Sofía logró romper la maldición y liberar a Leonardo de su tormento. El hombre lobo desapareció, y Lunavilla volvió a ser un pueblo pacífico.\n\nSin embargo, la leyenda dice que durante las noches de luna llena, aún se puede escuchar el aullido del hombre lobo en los bosques de Lunavilla, recordando la terrorífica maldición que una vez azotó la región.",
    "imageUrl": "https://i.ibb.co/pRzJZT7/freepik-candid-image-photography-natural-textures-highly-r-40872.jpg",
    "category": "Hombres lobo",
  },
  {
    "id_existing": 7,
    "title": "Noche Eterna",
    "description": "En un pueblo olvidado, donde las sombras bailan con la luna, una leyenda terrorífica se esconde en las tinieblas. \n La noche cayó sobre el pueblo como un velo de muerte. Las luces se apagaron, y las sombras comenzaron a moverse. En la plaza central, una figura emergió de las tinieblas. Era alto, pálido y ojos rojos brillantes. \n El vampiro se acercó a una joven llamada Sofía, que estaba sola en la plaza. Su sonrisa fue como un cuchillo afilado, y su aliento helado. Sofía intentó huir, pero sus pies estaban congelados de miedo. \n El vampiro comenzó a susurrar en el oído de Sofía, y ella sintió su mente siendo invadida por visiones terroríficas. Vio a sus seres queridos muertos, y a sí misma convertida en una criatura de la noche. \n Sofía intentó gritar, pero su voz estaba atrapada en su garganta. El vampiro se rió, y su risa fue como un eco en la noche. Luego, todo se volvió negro.",
    "imageUrl": "https://i.ibb.co/3Rnqr2h/genai-m4-pnb-nha-v3-upload-media-99788421-11-27-2024-19-45-13-490297-8380007223349417231.jpg",
    "category": "Vampiros",
  },
  {
    "id_existing": 8,
    "title": "Noche Oscura",
    "description": "En un pueblo abandonado, una leyenda terrorífica se esconde en las sombras. \n La noche cayó sobre el pueblo como un velo de muerte. Las luces se apagaron, y las sombras comenzaron a moverse.\nUn susurro se escuchó en la distancia, una voz femenina que llamaba a alguien.\n'Kikimora, Kikimora, ven y juega conmigo... \n Una figura emergió de las tinieblas. Era alta, delgada y pálida. Sus ojos brillaban como estrellas en la oscuridad.\nKikimora, la bruja del bosque, sonreía con malicia.\n'Jugaremos un juego de terror y muerte... \n La gente del pueblo comenzó a desaparecer. Algunos decían haber visto a Kikimora merodeando por las calles.\nOtros hablaban de extraños ruidos y sombras que se movían solas.\nLa noche se volvió más oscura y aterradora. \n Un grupo de valientes decidió enfrentar a Kikimora.\nSe adentraron en el bosque, pero nunca regresaron.\nLa leyenda dice que Kikimora sigue jugando con las almas de los desaparecidos.\nY que su susurro aún se escucha en la noche oscura...",
    "imageUrl": "https://i.ibb.co/5Bpx09T/genai-m4-lla-pnb-v3-upload-media-40115268-11-28-2024-16-29-50-113335-6940977549000334544.jpg",
    "category": "Kikimora",
  },
  {
    "id_existing": 11,
    "title": "El Susurro del Bosque",
    "description": "El aire se sentía pesado, cargado de una humedad que se pegaba a la piel como una segunda membrana.  El bosque de Blackwood era conocido por sus historias,",
    "imageUrl": "default_image_url.jpg",
    "category": "Slenderman",
  },
];